name: Node.js Continuous Integration

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build
        run: yarn build

      - name: Test
        run: yarn run test:ci
        env:
          CI: true
